---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Apps - Caddy - Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  extract_version:
    name: Extract Caddy Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Extract Caddy version
        id: extract_version
        run: |
          VERSION=$(grep -oP 'ARG CADDY_VERSION=\K[\d.]+' apps/caddy/Containerfile)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash

  release:
    name: Release Caddy Container Image
    uses: ./.github/workflows/rw-build-and-push-container.yaml
    needs:
      - extract_version
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    with:
      app_name: caddy
      app_version: ${{ needs.extract_version.outputs.version }}
      containerfile_path: apps/caddy/Containerfile
