---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR - Lint Renovate

on:
  pull_request:
    paths:
      - .renovaterc.json5
      - .renovate/**.json5

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changed-renovate-files: ${{ steps.changed-renovate-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Get all changed Renovate config files
        id: changed-renovate-files
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
        with:
          files: |
            .renovaterc.json5
            .renovate/**.json5
          matrix: true

  lint:
    name: Lint Renovate Config
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:42.66.9@sha256:5ae97929a05c5c2920935897a1dc4bff0b6f055ec627f86d2c02414dbf6feb96
      options: --user 0
    needs:
      - prepare
    strategy:
      matrix:
        files: ${{ fromJSON(needs.prepare.outputs.changed-renovate-files) }}
      fail-fast: false
      max-parallel: 4
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Validate Renovate Configuration
        run: |
          renovate-config-validator --strict ${{ matrix.files }}
        shell: bash
