---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR - Lint Renovate

on:
  pull_request:
    paths:
      - .renovaterc.json5
      - .renovate/**.json5

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changed-renovate-files: ${{ steps.changed-renovate-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get all changed Renovate config files
        id: changed-renovate-files
        uses: tj-actions/changed-files@8cba46e29c11878d930bca7870bb54394d3e8b21 # v47.0.2
        with:
          files: |
            .renovaterc.json5
            .renovate/**.json5
          matrix: true

  lint:
    name: Lint Renovate Config
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:43.31.1@sha256:99198d61d3c837085bdc94e0eafb1d57de3ecbfdc2e5e994817e589f71eacd16
      options: --user 0
    needs:
      - prepare
    strategy:
      matrix:
        files: ${{ fromJSON(needs.prepare.outputs.changed-renovate-files) }}
      fail-fast: false
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate Renovate Configuration
        run: |
          renovate-config-validator --strict ${{ matrix.files }}
        shell: bash
